export enum RouteNames {
  launch = 'Launch',
  authentication = 'authentication',
  login = 'Login',
  signUp = 'SignUp',
  resetPassword = 'ResetPassword',
  emailVerification = 'EmailVerification',
  newPassword = 'NewPassword',
  soicalLoginPassword = 'SocialLoginPassword',
  changePassword = 'ChangePassword',
  contactUs = 'ContactUs',
  home = 'Home',
  profile = 'Profile',
  profileEdit = 'ProfileEdit',
  analysis = 'Analysis',
  classes = 'Classes',
  aboutUs = 'About Us',
  faqs = 'Faqs',
  privacyPolicy = 'PrivacyPolicy',
  favorites = 'Favorites',
  settings = 'Settings',
  support = 'Support',
  subjectShow = 'SubjectShow',
  chapterShow = 'ChapterShow',
  exerciseShow = 'ExerciseShow',
  questionShow = 'QuestionShow',
  subjectToFavorites = 'SubjectToFavorites',
  video = 'Video',
  quiz = 'Quiz',
  quizShow = 'QuizShow',
  quizResult = 'QuizResult',
  quizResultOverview = 'QuizResultOverview',
  quizCheckCorrectAnswer = 'QuizCheckCorrectAnswer',
  pastPaper = 'PastPaper',
  pastPaperShow = 'PastPaperShow',
  topicShow = 'TopicShow',
  notifications = 'Notifications',
  continueStudyList = 'ContinueStudyList',
  appCornerImageShow = 'AppCornerImageShow',

  chapterExerciseTab = 'ChapterExerciseTab',
  chapterTopicsTab = 'ChapterTopicsTab',
  chapterTestsTab = 'ChapterTestsTab',

  exerciseQuestionTab = 'ExerciseQuestionTab',
  exerciseMcqsTab = 'ExerciseMcqsTab',

  videoStackShowExercise = 'VideoStackShowExercise',
  videoStackShowQuestion = 'VideoStackShowQuestion',

  quizStack = 'QuizStack',
  videoStack = 'VideoStack',
  subjectStack = 'SubjectStack',
  authStack = 'AuthStack',
  homeDrawer = 'HomeDrawer',
  homeTabar = 'HomeTabar',
  homeStack = 'HomeStack',
  storybook = 'Storybook',
  pastPaperStack = 'PastPaperStack',
}
